version: '2'
services:
  seed_node:
    image: "datastax/dse-server:6.7.8"
    environment:
      - DS_LICENSE=accept
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - 9042:9042 # make accessible from DSE studio in vm host browser
  node:
    image: "datastax/dse-server:6.7.8"
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
    links:
      - seed_node
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
